grafana:
  grafana.ini:
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
      org_role: Viewer

prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi
    retention: 3d

grafana:
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi
