all:
  children:
    control_plane:
      hosts:
        pi-brain:
          ansible_host: 10.0.0.1
    workers:
      hosts:
        pi-body:
          ansible_host: 10.0.0.2
        pi-3:
          ansible_host: 10.0.0.3
  vars:
    ansible_user: adrien
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
