grafana:
  grafana.ini:
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
      org_role: Viewer
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi
    retention: 3d
